// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwmLt_TKh0pU0pvz6J3tujklXY_TrFRA',
    appId: '1:982909792863:web:c8399562affa4592d7a1ea',
    messagingSenderId: '982909792863',
    projectId: 'flutter-starter-1273e',
    authDomain: 'flutter-starter-1273e.firebaseapp.com',
    storageBucket: 'flutter-starter-1273e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVldzAcK0u3iIIHfKj9pd6jn779ibrNto',
    appId: '1:982909792863:android:a97c48b1b5980c8dd7a1ea',
    messagingSenderId: '982909792863',
    projectId: 'flutter-starter-1273e',
    storageBucket: 'flutter-starter-1273e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKS0RBN8afwW7gFtB-AmVQ1ZAe_cHXy0',
    appId: '1:982909792863:ios:1ef21093835dd141d7a1ea',
    messagingSenderId: '982909792863',
    projectId: 'flutter-starter-1273e',
    storageBucket: 'flutter-starter-1273e.appspot.com',
    iosBundleId: 'com.example.firebaseExp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKS0RBN8afwW7gFtB-AmVQ1ZAe_cHXy0',
    appId: '1:982909792863:ios:14b5be8eef8948b0d7a1ea',
    messagingSenderId: '982909792863',
    projectId: 'flutter-starter-1273e',
    storageBucket: 'flutter-starter-1273e.appspot.com',
    iosBundleId: 'com.example.firebaseExp.RunnerTests',
  );
}
